version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    command: ["uv", "run", "uvicorn", "src.api:app", "--host", "0.0.0.0", "--port", "8000"]
    
  app:
    build: .
    ports:
      - "8501:8501"
    environment:
      - DOCKER_ENV=true
      - COMPOSE_ENV=true
    command: ["uv", "run", "streamlit", "run", "src/app.py", "--server.port", "8501", "--server.address", "0.0.0.0"]
    depends_on:
      - api
